# Generated by Django 2.2 on 2022-01-27 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20220126_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата'),
        ),
    ]
