# Generated by Django 2.2 on 2022-01-27 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_auto_20220127_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
    ]
