# Generated by Django 2.2 on 2022-01-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20220127_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
    ]
