# Generated by Django 2.2 on 2022-01-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_remove_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='czk',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='krona'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='eur',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='euro'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='pln',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='zloty'),
        ),
    ]
