# Generated by Django 2.2 on 2022-01-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
    ]
