# Generated by Django 2.2 on 2022-01-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('eur', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='euro')),
                ('pln', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='zloty')),
                ('czk', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='krona')),
            ],
        ),
    ]
