# Generated by Django 2.2 on 2022-01-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
    ]
