# Generated by Django 2.2 on 2022-01-26 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
